---
- hosts: webservers

  tasks:
  - name: Add lines to docker file
    lineinfile:
      path: /home/devasc/Documents/ansible-project/Dockerfile
      line: |
        FROM httpd:alpine
        COPY ./225095238_website/index.html /usr/local/apache2/htdocs/
        EXPOSE 80
        CMD ["httpd-foreground"]

  - name: stop and ignore existing container if present
    ignore_errors: yes
    command: docker rm -f hello

  - name: Build Docker image
    command: docker build -t website  /home/devasc/Documents/ansible-project

  - name: Run Dockerfile
    command: docker run -t -d -p 8098:80 --name hello --security-opt seccomp=unconfined website 